// frontend-onesdk-sample-angular-webpack/src/app/onboarding/onboarding.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from 'src/environments/environment';
import { EnvironmentConfigService } from '../environment-config.service';
import { OnesdkTokenService } from '../onesdk-token.service';
import OneSDK from '@frankieone/one-sdk';

@Component({
	selector: 'app-onboarding',
	templateUrl: './onboarding.component.html',
	styleUrls: ['./onboarding.component.css']
})
export class OnboardingComponent implements OnInit {
  private oneSdk: any;
	constructor(private tokenService: OnesdkTokenService, private envConfigService: EnvironmentConfigService) { }

	configurations = {
		async configureWelcomeOCR(configureWelcomeOCR: any) {
			let configWelcomeOCR: any = {
				name: "WELCOME"
			};

			if (configureWelcomeOCR === "true") {
				configWelcomeOCR = {
					name: "WELCOME",
					type: "manual",
					title: { label: "Config Title" },
					descriptions: [
						{ label: "Config Description Line 1", style: {} }
					],
					instructions: {
						content: [{ label: " Config Instructions" }],
						style: { "ff-instructions": { "font-family": "Helvetica" } }
					},
					cta: {
						label: "Config button",
						style: { "ff-button": { backgroundColor: "green" } }
					}
				};
			}
			return configWelcomeOCR;
		},

		async configureConsentOCR(configureConsentOCR: any) {
			let configConsentOCR: any = {
				name: "CONSENT"
			};

			if (configureConsentOCR === "true") {
				configConsentOCR = {
					name: "CONSENT",
					title: {
						label: "Config Consent Title",
						style: { "ff-title": { "font-family": "Cascadia code" } }
					},
					descriptions: [
						{ label: "Config Description 1", style: {} },
						{ label: "Config Description 2", style: {} },
						{ label: "Config Description 3", style: {} }
					],
					cta: {
						label: "Config Consent Button",
						style: { "ff-button": { backgroundColor: "green" } }
					}
				};
			}
			return configConsentOCR;
		},

		async configureDocumentIDOCR(
			configureDocumentIDOCR: any,
			configurePassportOCR: any,
			configureDriverOCR: any,
			configureMedicareOCR: any
		) {
			let configPassportOCR: any = "";
			let configDriverOCR: any = "";
			let configMedicareOCR: any = "";

			let configDocumentOCR: any = { name: "DOCUMENT", showPreps: true };

			if (configurePassportOCR === "true") {
				configPassportOCR = {
					type: "PASSPORT",
					label: "Config Passport"
				};
			}

			if (configureDriverOCR === "true") {
				configDriverOCR = {
					type: "DRIVERS_LICENCE",
					label: "Config Driver Licence"
				};
			}
			if (configureMedicareOCR === "true") {
				configMedicareOCR = {
					type: "NATIONAL_HEALTH_ID",
					label: "Config Medicare"
				};
			}

			if (configureDocumentIDOCR === "true") {
				configDocumentOCR = {
					name: "DOCUMENT",
					type: "ocr",
					title: { label: "Configure ID" },
					descriptions: [{ label: "Configure Description" }],
					documents: [
						configPassportOCR,
						configDriverOCR,
						configMedicareOCR
					]
				};
			}

			return configDocumentOCR;
		},
	};

	async ngOnInit() {    this.oneSdk = await OneSDK({
			session: await this.tokenService.getToken(),
			recipe: {
				ocr: {
					provideReviewScreen: false,
					maxDocumentCount: 1,
				},
				form: {
					provider: {
						name: 'react',
						googleApiKey: await this.envConfigService.getGoogleApiKey()
					}
				}
			},
		});

		const component = this.oneSdk.component as unknown as (arg0: any, arg1?: any) => any;

		const oneSdkIndividual = this.oneSdk.individual();
		oneSdkIndividual.addConsent("general");
		oneSdkIndividual.addConsent("docs");
		oneSdkIndividual.addConsent("creditheader");
		await oneSdkIndividual.submit();

		const welcome = component('form', await this.configurations.configureWelcomeOCR(true));
		const consent = component('form', await this.configurations.configureConsentOCR(true));
		const document = component('form', await this.configurations.configureDocumentIDOCR(true, true, true, true));
		const ocr = component('ocr');
		const review = component('form', {
			name: 'REVIEW',
		});
		welcome.on('form:welcome:ready', () => {
			consent.mount('#onboarding-container');
		});
		consent.on('form:consent:ready', () => {
			document.mount('#onboarding-container');
		});
		document.on('form:document:ready', () => {
			ocr.mount('#onboarding-container');
		});
		ocr.on('results', () => {
			review.mount('#onboarding-container');
		});

		welcome.mount('#onboarding-container');
	}
}
<div id="onboarding-container" style="min-width: 100vh; height: 85vh"></div>

// frontend-onesdk-sample-vue-vite/src/components/onesdk-test/Onboarding.vue
<script setup>
import { useOneSdkSession } from '@/composables/onesdk-session';
import { configurations } from '@/helper/onboarding.config';
import OneSDK from '@frankieone/one-sdk';
import { watchEffect } from 'vue';

const session = useOneSdkSession()
let welcome, consent, document, ocr, review

watchEffect(async () => {
	if (!session.value) return

	const oneSdk = await OneSDK({
		session: session.value,
		mode: "development",
		recipe: {
			ocr: {
				provideReviewScreen: false,
				maxDocumentCount: 1,
			},
			form: {
				provider: {
					name: 'react',
					googleApiKey: import.meta.env.VITE_GOOGLE_API_KEY
				}
			}
		},
	});

	const oneSdkIndividual = oneSdk.individual();
	oneSdkIndividual.addConsent("general");
	oneSdkIndividual.addConsent("docs");
	oneSdkIndividual.addConsent("creditheader");
	await oneSdkIndividual.submit();

	welcome = oneSdk.component('form', await configurations.configureWelcomeOCR(true));
	consent = oneSdk.component('form', await configurations.configureConsentOCR(true));
	document = oneSdk.component('form', await configurations.configureDocumentIDOCR(true, true, true, true));
	ocr = oneSdk.component('ocr');
	review = oneSdk.component('form', {
		name: 'REVIEW',
	});
	welcome.on('form:welcome:ready', () => {
		consent.mount('#onboarding-container');
	});
	consent.on('form:consent:ready', () => {
			document.mount('#onboarding-container');
	});
	document.on('form:document:ready', () => {
		ocr.mount('#onboarding-container');
	});
	ocr.on('results', () => {
		review.mount('#onboarding-container');
	});

	welcome.mount('#onboarding-container');
})
</script>

<template>
	<div id="onboarding-container" style="width: '100%'; height: 85vh"></div>
</template>
