// frontend-onesdk-sample-react-vite/src/flows/Sardine.jsx
"use client"
import { useEffect } from "react";
import useOneSDK from "../useOneSDK";

const Sardine = () => {
  const config = {
    mode: "development",
    recipe: {
      form: {
        provider: {
          name: "react",
          googleApiKey: ""   
        },
      },
    },
  };
  const alternateKey = true
  const { oneSDKInstance, error: errorOneSDK, loading } = useOneSDK({ config, alternateKey })
  
  const initOneSDK = async () => {
    const device = oneSDKInstance.component("device", {
        activityType: "REGISTRATION",
        //sessionId: "469368b5-f8aa-4b38-867b-5583db791185",
      });
      device.start();

      // 6. Add phone and email
      // oneSDKInstance.individual().setPhoneNumber("+61-0822082577");
      // oneSDKInstance.individual().setEmail("admin@riskybusiness.com");

      // 7. Initialise onboarding form
      const welcome = oneSDKInstance.component("form", {
        name: "WELCOME",
        mode: "individual",
        type: "manual",
      });

      const consent = oneSDKInstance.component("form", {
        name: "CONSENT",
        mode: "individual",
        type: "manual",
      });

      const personal = oneSDKInstance.component("form", {
        name: "PERSONAL",
        mode: "individual",
        type: "manual",
        personal: {
          countries:{
            default:{
              default:{
                fields:[
                 {
                    fieldType: 'input',
                    dataType: 'text',
                    label: 'Email',
                    name: 'extraData.email',
                    hide: false,
                    rules:{
                      required: {
                        value: true,
                        message: "Please enter your email"
                      }
                    }
                  },
                  {
                    fieldType: 'phone',
                    dataType: 'phone',
                    label: 'Phone Number',
                    name: 'extraData.phone',
                    hide: false,
                    placeholder: {
                      cc: "Code",
                      phoneNumber: "e.g. 0400 000 000"
                    },
                    options: [
                      {label: "AU +61", value: "+61"},
                      {label: "NZ +64", value: "+64"},
                      {label: "PH +63", value: "+63"},
                    ],
                    rules:{
                      required: {
                        value: true,
                        message: "Please enter your phone number"
                      }
                    }
                  },
                ]
              }
            }
          }
        }
      });

      const document = oneSDKInstance.component("form", {
        name: "DOCUMENT",
        mode: "individual",
        type: "manual",
      });

      const review = oneSDKInstance.component("form", {
        name: "REVIEW",
        mode: "individual",
        type: "manual",
        verify: true,
      });

      const retry = oneSDKInstance.component("form", {
        name: "RETRY",
        mode: "individual",
        type: "manual",
      });

      // const result = oneSDKInstance.component("form", {
      //   name: "RESULT",
      //   mode: "individual",
      //   type: "manual",
      //   state: "FAIL",
      // });

      welcome.on("form:welcome:ready", () => {
        consent.mount("#form-container-sardine");
      });

      consent.on("form:consent:ready", async () => {
        personal.mount("#form-container-sardine");
      });

      personal.on("form:personal:ready", async () => {
        document.mount("#form-container-sardine");
      });

      document.on("form:document:back", async () => {
        personal.mount("#form-container-sardine");
      });

      document.on("form:document:ready", async () => {
        review.mount("#form-container-sardine");
      });

      let count = 0;
      review.on("form:result:partial", async () => {
        if (count < 2) {
          retry.mount("#form-container-sardine");
          count += 1;
        }
      });

      welcome.mount("#form-container-sardine");
  }
    
  useEffect(() => {
    if(oneSDKInstance) {

      initOneSDK()
    }
  }, [oneSDKInstance])
  
  return (
    <>
      {loading && <div>Loading..</div>}
      {errorOneSDK && <div>{errorOneSDK}</div>}
      <div id='form-container-sardine'></div>
    </>
  )
}

export default Sardine

// frontend-onesdk-sample-vue-vite/src/components/onesdk-test/Sardine.vue
<script setup>
import { useOneSdkSession } from '@/composables/onesdk-session';
import { configurations } from '@/helper/onboarding.config';
import OneSDK from '@frankieone/one-sdk';
import { watchEffect } from 'vue';

const session = useOneSdkSession()

watchEffect(async () => {
	if (!session.value) return

	const oneSdk = await OneSDK({
		session: session.value,
		mode: "development",
		recipe: {
				form: {
					provider: {
						name: "react",
						googleApiKey: import.meta.env.VITE_GOOGLE_API_KEY
					}
				}
			},
	});

	// 4. Set recipe
	// oneSdk.individual().setProfileType('full');

	// 5. Initialise device module
	const device = oneSdk.component("device", {
		activityType: "REGISTRATION",
		//sessionId: "469368b5-f8aa-4b38-867b-5583db791185",
	});
	device.start();

	// 6. Add phone and email
	// oneSdk.individual().setPhoneNumber("+61-0822082577");
	// oneSdk.individual().setEmail("admin@riskybusiness.com");

	// 7. Initialise onboarding form
	const welcome = oneSdk.component("form", {
		name: "WELCOME",
		mode: "individual",
		type: "manual",
	});

	const consent = oneSdk.component("form", {
		name: "CONSENT",
		mode: "individual",
		type: "manual",
	});

	const personal = oneSdk.component("form", {
		name: "PERSONAL",
		mode: "individual",
		type: "manual",
		personal: {
			countries: {
				default: {
					default: {
						fields: [
							{
								fieldType: 'input',
								dataType: 'text',
								label: 'Email',
								name: 'extraData.email',
								hide: false,
								rules: {
									required: {
										value: true,
										message: "Please enter your email"
									}
								}
							},
							{
								fieldType: 'phone',
								dataType: 'phone',
								label: 'Phone Number',
								name: 'extraData.phone',
								hide: false,
								placeholder: {
									cc: "Code",
									phoneNumber: "e.g. 0400 000 000"
								},
								options: [
									{ label: "AU +61", value: "+61" },
									{ label: "NZ +64", value: "+64" },
									{ label: "PH +63", value: "+63" },
								],
								rules: {
									required: {
										value: true,
										message: "Please enter your phone number"
									}
								}
							},
						]
					}
				}
			}
		}
	});

	const document = oneSdk.component("form", {
		name: "DOCUMENT",
		mode: "individual",
		type: "manual",
	});

	const review = oneSdk.component("form", {
		name: "REVIEW",
		mode: "individual",
		type: "manual",
		verify: true,
	});

	const retry = oneSdk.component("form", {
		name: "RETRY",
		mode: "individual",
		type: "manual",
	});

	const result = oneSdk.component("form", {
		name: "RESULT",
		mode: "individual",
		type: "manual",
		state: "FAIL",
	});

	welcome.on("*", OneSDK.wildcardEventLogger);

	welcome.on("form:welcome:ready", () => {
		consent.mount("#sardine-container");
	});

	consent.on("form:consent:ready", async () => {
		personal.mount("#sardine-container");
	});

	personal.on("form:personal:ready", async () => {
		document.mount("#sardine-container");
	});

	document.on("form:document:back", async () => {
		personal.mount("#sardine-container");
	});

	document.on("form:document:ready", async () => {
		review.mount("#sardine-container");
	});

	let count = 0;
	review.on("form:result:partial", async () => {
		if (count < 2) {
			retry.mount("#sardine-container");
			count += 1;
		}
	});

	welcome.mount("#sardine-container");
})
</script>

<template>
	<div id="sardine-container" style="width: '100%'; height: 85vh"></div>
</template>
