// frontend-onesdk-sample-vue-webpack/src/components/onesdk-test/Idv.vue
<script setup>
import { useOneSdkSession } from '@/composables/onesdk-session';
import OneSDK from '@frankieone/one-sdk';
import { watchEffect } from 'vue';

const session = useOneSdkSession()
let idv

watchEffect(async () => {
	if (!session.value) return

	const oneSdk = await OneSDK({
		session: session.value,
		mode: "development",
	});

	idv = oneSdk.flow("idv");
	const oneSdkIndividual = oneSdk.individual();
	oneSdkIndividual.addConsent("general");
	oneSdkIndividual.addConsent("docs");
	oneSdkIndividual.addConsent("creditheader");
	await oneSdkIndividual.submit();

	idv.mount("#idv-dynamic");
})
</script>

<template>
	<div id="idv-dynamic" style="width: '100%'; height: 85vh"></div>
</template>

// frontend-onesdk-sample-angular-webpack/src/app/idv/idv.component.ts
import { Component, OnInit } from '@angular/core';
import { OnesdkTokenService } from '../onesdk-token.service';
import { environment } from 'src/environments/environment';
import OneSDK from '@frankieone/one-sdk';

@Component({
	selector: 'app-idv',
	templateUrl: './idv.component.html',
	styleUrls: ['./idv.component.css']
})
export class IdvComponent implements OnInit {
	constructor(private tokenService: OnesdkTokenService) { }

	async ngOnInit() {
		const oneSdk = await OneSDK({
			session: await this.tokenService.getToken(
				environment.CUSTOMER_ID,
				environment.API_KEY,
				environment.CUSTOMER_CHILD_ID
			),
		});

		const flow = oneSdk.flow as unknown as (arg0: any) => any;

		const idv = flow("idv");
		const oneSdkIndividual = oneSdk.individual();
		oneSdkIndividual.addConsent("general");
		oneSdkIndividual.addConsent("docs");
		oneSdkIndividual.addConsent("creditheader");
		await oneSdkIndividual.submit();

		idv.mount("#idv-dynamic");
	}
}
<div id="idv-dynamic" style="min-width: 100vh; height: 85vh"></div>
